version: '3.4'

services:
    async_db:
        image: postgres:latest
        container_name: async_db
        environment:
            - POSTGRES_DB=async
            - POSTGRES_USER=back
            - POSTGRES_PASSWORD=dristPasswd
        ports:
            - 5444:5432
        volumes:
            - async_db_data:/var/lib/postgresql/data

volumes:
    async_db_data: